parameters:
#    sportama_main.example.class: Sportama\MainBundle\Example

services:
#    sportama_main.example:
#        class: %sportama_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
